dist: xenial
language: python
sudo: true

python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"

before_install: |
  sudo apt-get -y install swig libmecab-dev mecab-ipadic-utf8

install: pip install tox-travis
script: tox -vvv
