# This is a Python package, but we don't use Travis's Python
# environment to build it, because of the complicated relationship it
# has with SWIG and the C++ MeCab library.  Instead we use tox,
# cibuildwheel, and a bunch of custom build scripts.

language: generic

matrix:
  include:
  - os: linux
    dist: xenial
    env: DRIVER=tox MECAB=system
  - os: linux
    dist: xenial
    env: DRIVER=tox MECAB=bundled
  - os: linux
    dist: xenial
    services: docker
    env: DRIVER=cibuildwheel MECAB=bundled CIBW_MANYLINUX_X86_64_IMAGE=manylinux1 CIBW_MANYLINUX_I686_IMAGE=manylinux1
  - os: linux
    dist: xenial
    services: docker
    env: DRIVER=cibuildwheel MECAB=bundled CIBW_MANYLINUX_X86_64_IMAGE=manylinux2010 CIBW_MANYLINUX_I686_IMAGE=manylinux2010
  - os: osx
    env: DRIVER=cibuildwheel MECAB=bundled

# Only run the deployment step if the build step succeeded.
# This prevents partial uploads in case the build crashed after
# building some but not all of the wheels.
script: |
  set -ex
  python3 ./scripts/travis-build.py
  python3 ./scripts/travis-deploy.py

# Deployment-related environment variables
env:
  global:
  - TWINE_USERNAME=23
  # TWINE_PASSWORD=[...]
  - secure: "dPai0WUJ5K8AGeOy1nWRfI7dKJ99XGcKGkhPwZ28dSZx851lBTtCE4Sb8YpLbOUTu9st5fiGmCEV3Y616fLruqXuil/7YIpyGt0HPiX/vxz0TopwcYdLshcw8b0N5y6tkaCYxljIQ+McSY7CUgtNW8vbZcykWy9De04hA43q5Rrb2JvW6QhT+DGOgxf34CMkMQw6QAHzjgEbrDbnVQxydEvGwtCfCby76KGVbWVocpQBJrOxJM+n5bBt091KJ6Ktkn/JemQDwaolZcYTXqu3fxZVVcDJLRzA3Mharj5P18UX7hQ3FnPbr/BWLDiicOf4i2z0Eu+q9XTK3FDRyP7tIReQTKXgBOcNBuvqMWGeqE/RYsHkDNihR/LKCNg2JC18MKyTGja/cleVcCUpvpzJX5w/nE79+UHL61yco6NmKUKHuP3GtHquzoqqz18thzYjw4E7lE8mcg6ewGj+nIxOE+UbqpuZHYXR+Rr+FiV1y5Szz5swXM+dTftAFIQujcCRD24nFuc5+uD21drlaH4Xpp9EAOx9BboBH/gSyagUEn+orXtmvtZdOUMGng/PU5wxN2tPhgKxI9Ay6VCvQ/J7iAI66ywrsoM/SnI9pgL1+B9aJ+kjvfQ9T4C0k6Nlqqu96S26D0Qald1P2s//fiUwMtP+o60DdcjYnP3MZ3awPos="
