language: generic

matrix:
  include:
    - os: linux
      dist: xenial
      env: DRIVER=tox MECAB=bundled
    - os: linux
      dist: xenial
      env: DRIVER=tox MECAB=system

script: ./scripts/travis-script.py
