language: generic

matrix:
  include:
    - os: linux
      dist: xenial
      env: DRIVER=tox MECAB=system
    - os: linux
      dist: xenial
      env: DRIVER=tox MECAB=bundled
    - os: linux
      dist: xenial
      services: docker
      env: DRIVER=cibuildwheel MECAB=bundled
    - os: osx
      env: DRIVER=cibuildwheel MECAB=bundled

script: exec python3 ./scripts/travis-script.py
