dist: xenial
language: python
sudo: true

python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"

env:
 - "MECAB=system"
 - "MECAB=bundled"

matrix:
  allow_failures:
    - env: MECAB=bundled

before_install: |
  pkg_deps=swig
  if [ $MECAB = system ]; then
    pkg_deps="$pkg_deps libmecab-dev mecab-ipadic-utf8"
  fi
  sudo apt-get -y install $pkg_deps

install: pip install tox-travis
script: tox -vvv
